name: Unit Tests

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        if: github.event_name == "pull_request"
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - uses: actions/checkout@v2
        if: github.event_name == "push"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: "x64"
      
      - name: Run Unit Tests
        run: |
          python -m unittest discover -s tests
